version: '3.8'
name: proyecto_curso

networks:
  mainNetwork:

services:
  api:
    container_name: curso_api
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mainNetwork
    depends_on:
      - db

  db:
    container_name: curso_db
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - mainNetwork

volumes:
  mysql_data: